name: FurryNets CI
run-name: ${{ github.actor }} is testing code
on:
  push:
    branch:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Full build app
        uses: actions/checkout@v2.3.2
        run: make full-build
