name: FurryNets CI
run-name: ${{ github.actor }} is testing code
on:
  push:
    branch:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install docker
        run: 
          sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && 
          sudo chmod +x /usr/local/bin/docker-compose &&
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose &&
          docker-compose --version

      - name: Build app
        run:
          sudo docker-compose up -d --build &&
          sudo docker-compose exec php composer install &&
          sudo docker-compose exec php artisan migrate &&
          sudo docker-compose run npm install &&
          sudo docker-compose run npm run build
      
      - name: Make seed
        run: sudo docker-compose exec php artisan db:seed
      
      - name: Testing app
        run: sudo docker-compose exec php artisan test
