name: FurryNets CI
run-name: ${{ github.actor }} is testing code
on:
  push:
    branch:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Full build app
        run: make full-build
      
      - name: Testing app
        run: make start
        run: make test
