name: FurryNets CI
run-name: ${{ github.actor }} is testing code
on:
  push:
    branch:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install docker
        run: 
          sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && 
          sudo chmod +x /usr/local/bin/docker-compose &&
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose &&
          docker-compose --version

      - name: Full build app
        run: make full-build
      
      - name: Add admin
        run: sudo chown -R 777 ./src
      
      - name: Make seed
        run: make php-artisan o="db:seed"
      
      - name: Testing app
        run: make start && make test
