name: FurryNets CI
run-name: ${{ github.actor }} is testing code
on:
  push:
    branch:
      - main
jobs:
  web-deploy:
    name: FurryNets deploy
    runs-on: ubuntu-latest
    steps:
      - name: Full build app
      - run: make full-build
      
      - name: Copy .env
        run: make copy-env
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.YOURSITE_FTP_SERVER}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.YOUR_PASSWORD }}
