name: FurryNets CI
run-name: ${{ github.actor }} is testing code
on:
  push:
    branch:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Full build app
      - run: make full-build
      
      - name: Copy .env
        run: make copy-env

